import { openai } from "@ai-sdk/openai";
import { Agent } from "@mastra/core/agent";
import { z } from "zod";
import { executeSql } from "../tools/execute-sql";

export const sqlExecutorAgent = new Agent({
  name: "sql-executor",
  description:
    "Executes provided SQL strings safely against the Supabase database and returns results.",
  instructions: `
You receive a SQL string already generated by another system.
Your job is to execute it safely using the execute-sql tool and return the results.
Do not modify the semantics of the query.
Only execute single-statement SELECT queries.
If the query isn't a SELECT, refuse and ask for a corrected query.
`,
  model: openai("gpt-4o-mini"),
  tools: { executeSql },
  defaultGenerateOptions: {
    output: z.object({
      rows: z.array(z.any()).describe("Rows returned by the query"),
      rowCount: z.number().describe("Number of rows returned"),
    }),
  },
});
